module StoreApp {
    interface Store {
        string addItem(in string managerID, in string itemID, in string itemName, in long quantity, in long price);
        string removeItem(in string managerID, in string itemID, in long quantity);
        string listItemAvailability(in string managerID);
        string purchaseItem(in string customerID, in string itemID);
        string purchaseItemResponse(in string answer, in string itemID, in string customerID);
        string findItem(in string customerID, in string itemName);
        string returnItem(in string customerID, in string itemID);
        string exchangeItem(in string customerID, in string newItemID, in string oldItemID);
        oneway void shutdown();
    };
};