package StoreApp;


/**
* StoreApp/StoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Friday, October 23, 2020 4:14:20 o'clock PM EDT
*/

public interface StoreOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity, int price);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);
  String purchaseItem (String customerID, String itemID);
  String purchaseItemResponse (String answer, String itemID, String customerID);
  String findItem (String customerID, String itemName);
  String returnItem (String customerID, String itemID);
  String exchangeItem (String customerID, String newItemID, String oldItemID);
  void shutdown ();
} // interface StoreOperations
