package StoreApp;


/**
* StoreApp/Store.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Friday, October 23, 2020 4:14:20 o'clock PM EDT
*/

public interface Store extends StoreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Store
